/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlavorsRouteImport } from './routes/flavors'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuildboxRouteImport } from './routes/buildbox'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as BoxesIndexRouteImport } from './routes/boxes.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as BoxesSlugRouteImport } from './routes/boxes.$slug'
import { Route as AdminUtmRouteImport } from './routes/admin.utm'
import { Route as AdminSocialRouteImport } from './routes/admin.social'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFlavorsRouteImport } from './routes/admin.flavors'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminBoxesRouteImport } from './routes/admin.boxes'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'

const FlavorsRoute = FlavorsRouteImport.update({
  id: '/flavors',
  path: '/flavors',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildboxRoute = BuildboxRouteImport.update({
  id: '/buildbox',
  path: '/buildbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesIndexRoute = BoxesIndexRouteImport.update({
  id: '/boxes/',
  path: '/boxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesSlugRoute = BoxesSlugRouteImport.update({
  id: '/boxes/$slug',
  path: '/boxes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtmRoute = AdminUtmRouteImport.update({
  id: '/utm',
  path: '/utm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlavorsRoute = AdminFlavorsRouteImport.update({
  id: '/flavors',
  path: '/flavors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoxesRoute = AdminBoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buildbox': typeof BuildboxRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/flavors': typeof FlavorsRoute
  '/admin/boxes': typeof AdminBoxesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flavors': typeof AdminFlavorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/utm': typeof AdminUtmRoute
  '/boxes/$slug': typeof BoxesSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/boxes/': typeof BoxesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buildbox': typeof BuildboxRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/flavors': typeof FlavorsRoute
  '/admin/boxes': typeof AdminBoxesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flavors': typeof AdminFlavorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/utm': typeof AdminUtmRoute
  '/boxes/$slug': typeof BoxesSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/boxes': typeof BoxesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buildbox': typeof BuildboxRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/flavors': typeof FlavorsRoute
  '/admin/boxes': typeof AdminBoxesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flavors': typeof AdminFlavorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/utm': typeof AdminUtmRoute
  '/boxes/$slug': typeof BoxesSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/boxes/': typeof BoxesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buildbox'
    | '/cart'
    | '/checkout'
    | '/flavors'
    | '/admin/boxes'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/faqs'
    | '/admin/flavors'
    | '/admin/login'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/utm'
    | '/boxes/$slug'
    | '/order/$id'
    | '/products/$slug'
    | '/admin/'
    | '/boxes/'
    | '/products/'
    | '/admin/orders/$id'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buildbox'
    | '/cart'
    | '/checkout'
    | '/flavors'
    | '/admin/boxes'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/faqs'
    | '/admin/flavors'
    | '/admin/login'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/utm'
    | '/boxes/$slug'
    | '/order/$id'
    | '/products/$slug'
    | '/admin'
    | '/boxes'
    | '/products'
    | '/admin/orders/$id'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buildbox'
    | '/cart'
    | '/checkout'
    | '/flavors'
    | '/admin/boxes'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/faqs'
    | '/admin/flavors'
    | '/admin/login'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/utm'
    | '/boxes/$slug'
    | '/order/$id'
    | '/products/$slug'
    | '/admin/'
    | '/boxes/'
    | '/products/'
    | '/admin/orders/$id'
    | '/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuildboxRoute: typeof BuildboxRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FlavorsRoute: typeof FlavorsRoute
  BoxesSlugRoute: typeof BoxesSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BoxesIndexRoute: typeof BoxesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/flavors': {
      id: '/flavors'
      path: '/flavors'
      fullPath: '/flavors'
      preLoaderRoute: typeof FlavorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildbox': {
      id: '/buildbox'
      path: '/buildbox'
      fullPath: '/buildbox'
      preLoaderRoute: typeof BuildboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/': {
      id: '/boxes/'
      path: '/boxes'
      fullPath: '/boxes/'
      preLoaderRoute: typeof BoxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$slug': {
      id: '/boxes/$slug'
      path: '/boxes/$slug'
      fullPath: '/boxes/$slug'
      preLoaderRoute: typeof BoxesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utm': {
      id: '/admin/utm'
      path: '/utm'
      fullPath: '/admin/utm'
      preLoaderRoute: typeof AdminUtmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social': {
      id: '/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flavors': {
      id: '/admin/flavors'
      path: '/flavors'
      fullPath: '/admin/flavors'
      preLoaderRoute: typeof AdminFlavorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/boxes': {
      id: '/admin/boxes'
      path: '/boxes'
      fullPath: '/admin/boxes'
      preLoaderRoute: typeof AdminBoxesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBoxesRoute: typeof AdminBoxesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminFlavorsRoute: typeof AdminFlavorsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSocialRoute: typeof AdminSocialRoute
  AdminUtmRoute: typeof AdminUtmRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBoxesRoute: AdminBoxesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminFlavorsRoute: AdminFlavorsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSocialRoute: AdminSocialRoute,
  AdminUtmRoute: AdminUtmRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BuildboxRoute: BuildboxRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FlavorsRoute: FlavorsRoute,
  BoxesSlugRoute: BoxesSlugRoute,
  OrderIdRoute: OrderIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BoxesIndexRoute: BoxesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
